apiVersion: v1
kind: Pod
metadata:
  name: results-app
  labels:
    app: voting-app
    component: results-app
spec:
  containers:
    - name: results-app
      image: dockersamples/examplevotingapp_result
---
apiVersion: v1
kind: Service
metadata:
  name: results-app
spec:
  type: NodePort
  selector:
    app: voting-app
    component: results-app
  ports:
    - port: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: result2.0
spec:
  rules:
    - host: results.local.mikesir87.training
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: results-app
                port:
                  number: 5000