apiVersion: v1
kind: Pod
metadata:
  name: voting-app
  labels:
    app: voting-app
    component: voting-app
spec:
  containers:
    - name: voting-app
      image: dockersamples/examplevotingapp_vote:before
---
apiVersion: v1
kind: Service
metadata:
  name: voting-app
spec:
  type: NodePort
  selector:
    app: voting-app
    component: voting-app
  ports:
    - port: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vote2.0
spec:
  rules:
    - host: voting.local.mikesir87.training
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: voting-app
                port:
                  number: 5000